[package]
name = "skewb_class_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_for = "0.1.3"
rand = "0.8.5"
rayon = "1.8.1"
rustc-hash = "1.1.0"
